- name: Set nvml-agent dir
  set_fact:
    nvml_agent_dir : "/etc/nvml-agent"

- name: Ensure NVML agent dir
  file:
    path: "{{ nvml_agent_dir }}"
    state: directory

- name: Install NVML Agent Scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ nvml_agent_dir }}/{{ item }}"
  with_items:
    - "conf.yaml"
    - "logging.yaml"
    - "get-pod-from-pid.sh"
    - "nvml-agent.py"
    - "start"

- name: Changing NVML Agent Scripts Permissions (+x)
  file:
    dest: "{{ nvml_agent_dir }}/{{ item }}"
    mode: a+x
  with_items:
    - "get-pod-from-pid.sh"
    - "nvml-agent.py"
    - "start"

- name: Install NVML Agent service
  template:
    src: "nvml_agent.service.j2"
    dest: "/etc/systemd/system/nvml_agent.service"

- name: Ensure NVML agent logging dir
  file:
    path: "/var/log/nvml-agent"
    state: directory

- name: Reload Daemon
  command: systemctl daemon-reload

- name: enable service nvml-agent and ensure it is not masked
  systemd:
    name: nvml_agent
    enabled: yes
    masked: no

- name: Make sure a service is running
  systemd: 
    state: started 
    name: nvml_agent