- name: Set nvml-agent dir
  set_fact:
    nvml_agent_dir : "/etc/nvml-agent"

- name: Ensure NVML agent dir
  become: True
  file:
    path: "{{ nvml_agent_dir }}"
    state: directory

- name: Install NVML Agent Scripts
  become: True
  template:
    src: "{{ item }}.j2"
    dest: "{{ nvml_agent_dir }}/{{ item }}"
  with_items:
    - "conf.yaml"
    - "logging.yaml"
    - "get-pod-from-pid.sh"
    - "nvml-agent.py"
    - "start"

- name: Changing NVML Agent Scripts Permissions (+x)
  become: True
  file:
    dest: "{{ nvml_agent_dir }}/{{ item }}"
    mode: a+x
  with_items:
    - "get-pod-from-pid.sh"
    - "nvml-agent.py"
    - "start"

- name: Install NVML Agent service
  become: True
  template:
    src: "nvml_agent.service.j2"
    dest: "/etc/systemd/system/nvml_agent.service"

- name: Ensure NVML agent logging dir
  become: True
  file:
    path: "/var/log/nvml-agent"
    state: directory

- name: Reload Daemon
  become: True
  systemd: daemon_reload=yes

- name: enable service nvml-agent and ensure it is not masked
  become: True 
  systemd:
    name: nvml_agent
    enabled: yes
    masked: no

- name: Make sure a service is running
  become: True
  systemd: state=started name=nvml_agent